/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import classes.Db;
import java.awt.CardLayout;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import classes.LoginClass;
import classes.ManageAdmin;
import classes.ManageOfficer;
import classes.ManageUser;
import classes.UserType;
import java.sql.PreparedStatement;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hansani Perera
 */
public class Admin extends javax.swing.JFrame {
    
    Home hp;
    ManageUser user =new ManageUser();
    private static PreparedStatement pst1;
    ManageOfficer off =new ManageOfficer();
    ManageAdmin ad =new ManageAdmin();
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setDefaultCloseOperation(Admin.DISPOSE_ON_CLOSE);
        displayPanel("card3");
    }
    
    private void displayPanel(String card){
        CardLayout cl= (CardLayout)rightP.getLayout();
        cl.show(rightP, card);
    }
    
       
    /**
     *
     * @return
     */
    public javax.swing.JTable getTable(){
        return jUsersTbl;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightP = new javax.swing.JPanel();
        jDeletePanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jUsersTbl = new javax.swing.JTable();
        jDeleteBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addUserP = new javax.swing.JPanel();
        jAddUserLbl2 = new javax.swing.JLabel();
        jUserTypeLbl2 = new javax.swing.JLabel();
        jAddressLbl2 = new javax.swing.JLabel();
        jNICLbl2 = new javax.swing.JLabel();
        jEmailLbl2 = new javax.swing.JLabel();
        jPwdLbl2 = new javax.swing.JLabel();
        jConfirmPwdLbl4 = new javax.swing.JLabel();
        addB = new javax.swing.JButton();
        aaddT = new javax.swing.JTextField();
        ausernameT = new javax.swing.JTextField();
        jConfirmPwdLbl5 = new javax.swing.JLabel();
        aemailT = new javax.swing.JTextField();
        apwdF = new javax.swing.JPasswordField();
        jNameLbl4 = new javax.swing.JLabel();
        jNameLbl5 = new javax.swing.JLabel();
        fnameT1 = new javax.swing.JTextField();
        lnameT1 = new javax.swing.JTextField();
        atelT = new javax.swing.JTextField();
        jPwdLbl4 = new javax.swing.JLabel();
        acpwdF = new javax.swing.JPasswordField();
        userCombo = new javax.swing.JComboBox<>();
        anicT = new javax.swing.JTextField();
        clearPB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        adminP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UpdateUserP = new javax.swing.JPanel();
        jAddUserLbl3 = new javax.swing.JLabel();
        jUserTypeLbl3 = new javax.swing.JLabel();
        jAddressLbl3 = new javax.swing.JLabel();
        jNICLbl5 = new javax.swing.JLabel();
        jEmailLbl3 = new javax.swing.JLabel();
        jPwdLbl3 = new javax.swing.JLabel();
        jConfirmPwdLbl6 = new javax.swing.JLabel();
        updateB = new javax.swing.JButton();
        aaddT1 = new javax.swing.JTextField();
        ausernameT1 = new javax.swing.JTextField();
        jConfirmPwdLbl7 = new javax.swing.JLabel();
        aemailT1 = new javax.swing.JTextField();
        apwdF1 = new javax.swing.JPasswordField();
        jNameLbl8 = new javax.swing.JLabel();
        jNameLbl9 = new javax.swing.JLabel();
        fnameT2 = new javax.swing.JTextField();
        lnameT2 = new javax.swing.JTextField();
        atelT1 = new javax.swing.JTextField();
        jPwdLbl7 = new javax.swing.JLabel();
        acpwdF1 = new javax.swing.JPasswordField();
        userCombo2 = new javax.swing.JComboBox<>();
        clearPB1 = new javax.swing.JButton();
        unicCombo = new javax.swing.JComboBox<>();
        backB1 = new javax.swing.JButton();
        leftP = new javax.swing.JPanel();
        jAddUserBtn = new javax.swing.JButton();
        jUpdateUserBtn = new javax.swing.JButton();
        jDeleteUserBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rightP.setLayout(new java.awt.CardLayout());

        jDeletePanel.setBackground(new java.awt.Color(255, 255, 255));

        jUsersTbl.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jUsersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NIC", "Username"
            }
        ));
        jScrollPane5.setViewportView(jUsersTbl);

        jDeleteBtn.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jDeleteBtn.setText("Delete");
        jDeleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Delete Users");

        javax.swing.GroupLayout jDeletePanelLayout = new javax.swing.GroupLayout(jDeletePanel);
        jDeletePanel.setLayout(jDeletePanelLayout);
        jDeletePanelLayout.setHorizontalGroup(
            jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeletePanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDeletePanelLayout.createSequentialGroup()
                .addGroup(jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDeletePanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDeleteBtn))
                    .addGroup(jDeletePanelLayout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        jDeletePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jDeleteBtn});

        jDeletePanelLayout.setVerticalGroup(
            jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDeletePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteBtn)
                    .addComponent(jButton1))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jDeletePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jDeleteBtn});

        rightP.add(jDeletePanel, "card7");

        addUserP.setBackground(new java.awt.Color(255, 255, 255));

        jAddUserLbl2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jAddUserLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddUserLbl2.setText("Add User");

        jUserTypeLbl2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jUserTypeLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserTypeLbl2.setText("User Type");
        jUserTypeLbl2.setToolTipText("");

        jAddressLbl2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jAddressLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddressLbl2.setText("Address");

        jNICLbl2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jNICLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNICLbl2.setText("NIC");

        jEmailLbl2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jEmailLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmailLbl2.setText("E-mail");

        jPwdLbl2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPwdLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPwdLbl2.setText("Password");

        jConfirmPwdLbl4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jConfirmPwdLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConfirmPwdLbl4.setText("Confirm Password");

        addB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        addB.setText("Add");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        aaddT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaddTActionPerformed(evt);
            }
        });

        jConfirmPwdLbl5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jConfirmPwdLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConfirmPwdLbl5.setText("Telephone ");

        aemailT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aemailTActionPerformed(evt);
            }
        });

        apwdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apwdFActionPerformed(evt);
            }
        });

        jNameLbl4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jNameLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNameLbl4.setText("First Name");

        jNameLbl5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jNameLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNameLbl5.setText("Last Name");

        fnameT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameT1ActionPerformed(evt);
            }
        });

        lnameT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameT1ActionPerformed(evt);
            }
        });

        atelT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atelTActionPerformed(evt);
            }
        });

        jPwdLbl4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPwdLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPwdLbl4.setText("Username");

        acpwdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acpwdFActionPerformed(evt);
            }
        });

        userCombo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        userCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        anicT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anicTActionPerformed(evt);
            }
        });

        clearPB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        clearPB.setText("Clear");
        clearPB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPBActionPerformed(evt);
            }
        });

        backB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        backB.setText("Back");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addUserPLayout = new javax.swing.GroupLayout(addUserP);
        addUserP.setLayout(addUserPLayout);
        addUserPLayout.setHorizontalGroup(
            addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPwdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jConfirmPwdLbl4)
                        .addComponent(jNameLbl4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAddressLbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jEmailLbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPwdLbl4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jUserTypeLbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jConfirmPwdLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNICLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addUserPLayout.createSequentialGroup()
                            .addComponent(backB)
                            .addGap(39, 39, 39)
                            .addComponent(addB)
                            .addGap(36, 36, 36)
                            .addComponent(clearPB))
                        .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(aemailT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aaddT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(addUserPLayout.createSequentialGroup()
                                        .addComponent(fnameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jNameLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lnameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addUserPLayout.createSequentialGroup()
                                        .addComponent(anicT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(243, 243, 243)))
                                .addComponent(atelT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(apwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acpwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                        .addComponent(ausernameT, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAddUserLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );

        addUserPLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addB, backB, clearPB});

        addUserPLayout.setVerticalGroup(
            addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddUserLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anicT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNICLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirmPwdLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atelT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddressLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aaddT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aemailT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserTypeLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ausernameT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwdLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirmPwdLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acpwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(addUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearPB)
                    .addComponent(addB)
                    .addComponent(backB))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        rightP.add(addUserP, "card6");

        adminP.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/admin-with-cogwheels.png"))); // NOI18N

        javax.swing.GroupLayout adminPLayout = new javax.swing.GroupLayout(adminP);
        adminP.setLayout(adminPLayout);
        adminPLayout.setHorizontalGroup(
            adminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        adminPLayout.setVerticalGroup(
            adminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        rightP.add(adminP, "card3");

        UpdateUserP.setBackground(new java.awt.Color(255, 255, 255));

        jAddUserLbl3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jAddUserLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddUserLbl3.setText("Update User");

        jUserTypeLbl3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jUserTypeLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserTypeLbl3.setText("User Type");
        jUserTypeLbl3.setToolTipText("");

        jAddressLbl3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jAddressLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddressLbl3.setText("Address");

        jNICLbl5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jNICLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNICLbl5.setText("NIC");

        jEmailLbl3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jEmailLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmailLbl3.setText("E-mail");

        jPwdLbl3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPwdLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPwdLbl3.setText("Password");

        jConfirmPwdLbl6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jConfirmPwdLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConfirmPwdLbl6.setText("Confirm Password");

        updateB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        updateB.setText("Update");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        aaddT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaddT1ActionPerformed(evt);
            }
        });

        ausernameT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausernameT1ActionPerformed(evt);
            }
        });

        jConfirmPwdLbl7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jConfirmPwdLbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConfirmPwdLbl7.setText("Telephone ");

        aemailT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aemailT1ActionPerformed(evt);
            }
        });

        apwdF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apwdF1ActionPerformed(evt);
            }
        });

        jNameLbl8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jNameLbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNameLbl8.setText("First Name");

        jNameLbl9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jNameLbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNameLbl9.setText("Last Name");

        fnameT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameT2ActionPerformed(evt);
            }
        });

        lnameT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameT2ActionPerformed(evt);
            }
        });

        atelT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atelT1ActionPerformed(evt);
            }
        });

        jPwdLbl7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPwdLbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPwdLbl7.setText("Username");

        acpwdF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acpwdF1ActionPerformed(evt);
            }
        });

        userCombo2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        userCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        clearPB1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        clearPB1.setText("Clear");
        clearPB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearPB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPB1ActionPerformed(evt);
            }
        });

        unicCombo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        backB1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        backB1.setText("Back");
        backB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateUserPLayout = new javax.swing.GroupLayout(UpdateUserP);
        UpdateUserP.setLayout(UpdateUserPLayout);
        UpdateUserPLayout.setHorizontalGroup(
            UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAddUserLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserPLayout.createSequentialGroup()
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateUserPLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNameLbl8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNICLbl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmailLbl3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPwdLbl7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUserTypeLbl3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jConfirmPwdLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAddressLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UpdateUserPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPwdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateUserPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jConfirmPwdLbl6)))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aaddT1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aemailT1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateUserPLayout.createSequentialGroup()
                        .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateUserPLayout.createSequentialGroup()
                                .addComponent(fnameT2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jNameLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lnameT2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(unicCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userCombo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateUserPLayout.createSequentialGroup()
                                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(backB1)
                                    .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ausernameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(acpwdF1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(atelT1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apwdF1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addComponent(updateB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearPB1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        UpdateUserPLayout.setVerticalGroup(
            UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserPLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jAddUserLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameT2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameT2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNICLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(unicCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirmPwdLbl7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(atelT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddressLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aaddT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aemailT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmailLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserTypeLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ausernameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwdLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apwdF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acpwdF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConfirmPwdLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129)
                .addGroup(UpdateUserPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backB1)
                    .addComponent(updateB)
                    .addComponent(clearPB1))
                .addGap(42, 42, 42))
        );

        rightP.add(UpdateUserP, "card5");

        getContentPane().add(rightP, java.awt.BorderLayout.CENTER);

        leftP.setBackground(new java.awt.Color(153, 204, 255));
        leftP.setForeground(new java.awt.Color(153, 204, 255));

        jAddUserBtn.setBackground(new java.awt.Color(153, 204, 255));
        jAddUserBtn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jAddUserBtn.setText("Add User");
        jAddUserBtn.setBorderPainted(false);
        jAddUserBtn.setContentAreaFilled(false);
        jAddUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAddUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddUserBtnActionPerformed(evt);
            }
        });

        jUpdateUserBtn.setBackground(new java.awt.Color(153, 204, 255));
        jUpdateUserBtn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jUpdateUserBtn.setText("Update User");
        jUpdateUserBtn.setBorderPainted(false);
        jUpdateUserBtn.setContentAreaFilled(false);
        jUpdateUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jUpdateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateUserBtnActionPerformed(evt);
            }
        });

        jDeleteUserBtn.setBackground(new java.awt.Color(153, 204, 255));
        jDeleteUserBtn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jDeleteUserBtn.setText("Delete User");
        jDeleteUserBtn.setBorderPainted(false);
        jDeleteUserBtn.setContentAreaFilled(false);
        jDeleteUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDeleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPLayout = new javax.swing.GroupLayout(leftP);
        leftP.setLayout(leftPLayout);
        leftPLayout.setHorizontalGroup(
            leftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeleteUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUpdateUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jAddUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        leftPLayout.setVerticalGroup(
            leftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jAddUserBtn)
                .addGap(160, 160, 160)
                .addComponent(jUpdateUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jDeleteUserBtn)
                .addGap(100, 100, 100))
        );

        getContentPane().add(leftP, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed

            int row = jUsersTbl.getSelectedRow();
            int nic =(int) jUsersTbl.getValueAt(row,0);
        
            try {
            pst1 = Db.connection().prepareStatement("delete from admin where nic =?");
            pst1.setInt(1, nic);
            pst1.executeUpdate();
            pst1 = Db.connection().prepareStatement("delete from person where nic =?");
            pst1.setInt(1, nic);
            pst1.executeUpdate();
            System.out.println("DELETED SUCCESSFULLY");
            
            if(row != -1) {
            DefaultTableModel model = (DefaultTableModel)jUsersTbl.getModel();
            model.removeRow(row);
            }
            
            } catch (SQLIntegrityConstraintViolationException ex) {
                try {
                    pst1 = Db.connection().prepareStatement("delete from officer where nic =?");
                    pst1.setInt(1, nic);
                    pst1.executeUpdate();
                    pst1 = Db.connection().prepareStatement("delete from person where nic =?");
                    pst1.setInt(1, nic);
                    pst1.executeUpdate();
                } catch (SQLException ex1) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
            catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                    
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void aemailTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aemailTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aemailTActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        // TODO add your handling code here:
                   //(String fname,String lname,String userName,String nic,String pid, String password, String email , String tel,String address)     
                 
                 
            if((apwdF.getText().equals(acpwdF.getText()))){
                try {
                    if(0>Integer.parseInt(anicT.getText())){
                        JOptionPane.showMessageDialog(this, "Please fill all the details");
                    }else
                        user.addUser(lnameT1.getText(), fnameT1.getText(), Integer.parseInt(atelT.getText()), aaddT.getText(),Integer.parseInt(anicT.getText()),aemailT.getText());
                    
                    
                    
                    if(userCombo.getSelectedItem()=="OFFICER"){
                        try {
                            int loadId = off.loadId();
                            off.addUser(loadId,ausernameT.getText(),Integer.parseInt(anicT.getText()),apwdF.getText());
                        } catch (SQLException ex) {
                            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        
                        int loadId1 = ad.loadId();
                        ad.addUser(loadId1,ausernameT.getText(),apwdF.getText(),Integer.parseInt(anicT.getText()));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
                   
            }
            else{
                JOptionPane.showMessageDialog(this, "Password fields do not match");
            } 
    }//GEN-LAST:event_addBActionPerformed

    private void jAddUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddUserBtnActionPerformed
              
            userCombo.removeAllItems();
            userCombo.addItem(UserType.ADMIN.name());
            userCombo.addItem(UserType.OFFICER.name());
            displayPanel("card6");
       
    }//GEN-LAST:event_jAddUserBtnActionPerformed

    private void jUpdateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateUserBtnActionPerformed
            
            unicCombo.removeAllItems();
            userCombo2.removeAllItems();
        try {
            // TODO add your handling code here:
            
            userCombo2.addItem(UserType.ADMIN.name());
            userCombo2.addItem(UserType.OFFICER.name());
            int[] nic;
            
            nic = ad.loadAdminOfficerId();
            
            for (int i = 0; i < nic.length; i++) {
                
                if(nic[i]!=0){
                    unicCombo.addItem(Integer.toString(nic[i]));
                    
                }
            }
           displayPanel("card5");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jUpdateUserBtnActionPerformed

    private void jDeleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteUserBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jUsersTbl.getModel();
        model.setRowCount(0);
        try {
            ManageUser.setUserInfo(model);
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayPanel("card7");
    }//GEN-LAST:event_jDeleteUserBtnActionPerformed

    private void fnameT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameT1ActionPerformed

    private void lnameT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameT1ActionPerformed

    private void atelTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atelTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atelTActionPerformed

    private void acpwdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acpwdFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acpwdFActionPerformed

    private void anicTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anicTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anicTActionPerformed

    private void clearPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPBActionPerformed
        // TODO add your handling code here:
        this.fnameT1.setText(null);
        this.lnameT1.setText(null);
        this.aaddT.setText(null);
        this.aemailT.setText(null);
        this.atelT.setText(null);
        this.anicT.setText(null);
        this.ausernameT.setText(null);
        this.apwdF.setText(null);
        this.acpwdF.setText(null);
    }//GEN-LAST:event_clearPBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        // TODO add your handling code here:
            
            userCombo2.removeAllItems();
            //unicCombo.removeAllItems();
            userCombo2.addItem(UserType.ADMIN.name());
            userCombo2.addItem(UserType.OFFICER.name());
        if((apwdF1.getText().equals(acpwdF1.getText()))){
             try {
            user.updateUser(lnameT2.getText(), fnameT2.getText(), atelT1.getText(), aaddT1.getText(),Integer.parseInt(String.valueOf(unicCombo.getSelectedItem())),aemailT1.getText());
            
               
                                   
                    if(userCombo2.getSelectedItem()=="OFFICER"){
                        int loadId = off.loadId();
                        off.updateUser(loadId,ausernameT.getText(),apwdF.getText(),Integer.parseInt(String.valueOf(unicCombo.getSelectedItem())));
                    }else{
                        
                        int loadId1 = ad.loadId();
                        ad.updateUser(loadId1,ausernameT.getText(),apwdF.getText(),Integer.parseInt(String.valueOf(unicCombo.getSelectedItem())));
                    }
                    
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "username already exist \n please change your user name");
                }    catch (SQLException ex) {
                         Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                     }
            }
            else{
                JOptionPane.showMessageDialog(this, "Password fields do not match");
            }
       
    }//GEN-LAST:event_updateBActionPerformed

    private void aemailT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aemailT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aemailT1ActionPerformed

    private void fnameT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameT2ActionPerformed

    private void lnameT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameT2ActionPerformed

    private void atelT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atelT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atelT1ActionPerformed

    private void acpwdF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acpwdF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acpwdF1ActionPerformed

    private void clearPB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPB1ActionPerformed
        // TODO add your handling code here:
        this.fnameT2.setText(null);
        this.lnameT2.setText(null);
        this.aaddT1.setText(null);
        this.aemailT1.setText(null);
        this.atelT1.setText(null);
        this.ausernameT1.setText(null);
        this.apwdF1.setText(null);
        this.acpwdF1.setText(null);
        
    }//GEN-LAST:event_clearPB1ActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed

        // TODO add your handling code here:
        displayPanel("card3");
    }//GEN-LAST:event_backBActionPerformed

    private void backB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backB1ActionPerformed

        // TODO add your handling code here:
        displayPanel("card3");
    }//GEN-LAST:event_backB1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        displayPanel("card3");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aaddTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaddTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aaddTActionPerformed

    private void apwdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apwdFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apwdFActionPerformed

    private void aaddT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaddT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aaddT1ActionPerformed

    private void apwdF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apwdF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apwdF1ActionPerformed

    private void ausernameT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausernameT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ausernameT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateUserP;
    private javax.swing.JTextField aaddT;
    private javax.swing.JTextField aaddT1;
    private javax.swing.JPasswordField acpwdF;
    private javax.swing.JPasswordField acpwdF1;
    private javax.swing.JButton addB;
    private javax.swing.JPanel addUserP;
    private javax.swing.JPanel adminP;
    private javax.swing.JTextField aemailT;
    private javax.swing.JTextField aemailT1;
    private javax.swing.JTextField anicT;
    private javax.swing.JPasswordField apwdF;
    private javax.swing.JPasswordField apwdF1;
    private javax.swing.JTextField atelT;
    private javax.swing.JTextField atelT1;
    private javax.swing.JTextField ausernameT;
    private javax.swing.JTextField ausernameT1;
    private javax.swing.JButton backB;
    private javax.swing.JButton backB1;
    private javax.swing.JButton clearPB;
    private javax.swing.JButton clearPB1;
    private javax.swing.JTextField fnameT1;
    private javax.swing.JTextField fnameT2;
    private javax.swing.JButton jAddUserBtn;
    private javax.swing.JLabel jAddUserLbl2;
    private javax.swing.JLabel jAddUserLbl3;
    private javax.swing.JLabel jAddressLbl2;
    private javax.swing.JLabel jAddressLbl3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jConfirmPwdLbl4;
    private javax.swing.JLabel jConfirmPwdLbl5;
    private javax.swing.JLabel jConfirmPwdLbl6;
    private javax.swing.JLabel jConfirmPwdLbl7;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JPanel jDeletePanel;
    private javax.swing.JButton jDeleteUserBtn;
    private javax.swing.JLabel jEmailLbl2;
    private javax.swing.JLabel jEmailLbl3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNICLbl2;
    private javax.swing.JLabel jNICLbl5;
    private javax.swing.JLabel jNameLbl4;
    private javax.swing.JLabel jNameLbl5;
    private javax.swing.JLabel jNameLbl8;
    private javax.swing.JLabel jNameLbl9;
    private javax.swing.JLabel jPwdLbl2;
    private javax.swing.JLabel jPwdLbl3;
    private javax.swing.JLabel jPwdLbl4;
    private javax.swing.JLabel jPwdLbl7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jUpdateUserBtn;
    private javax.swing.JLabel jUserTypeLbl2;
    private javax.swing.JLabel jUserTypeLbl3;
    private javax.swing.JTable jUsersTbl;
    private javax.swing.JPanel leftP;
    private javax.swing.JTextField lnameT1;
    private javax.swing.JTextField lnameT2;
    private javax.swing.JPanel rightP;
    private javax.swing.JComboBox<String> unicCombo;
    private javax.swing.JButton updateB;
    private javax.swing.JComboBox<String> userCombo;
    private javax.swing.JComboBox<String> userCombo2;
    // End of variables declaration//GEN-END:variables
}
